log_reg:
  solver: 'lbfgs'
  max_iter: 1000
  verbose: 1



random_forest:
  cv: 5
  param_grid: 
    n_estimators: [200, 500]
    max_features: ['auto', 'sqrt']
    max_depth : [4,5,100]
    criterion : ['gini', 'entropy']