defaults:
  - _self_  # Stuff from this file will be overwritten by the selected defaults.
  - models: model_default
  - wandb: wandb_default

seed: 42
log_level: info  # debug, info, warning, error, critical
auto: True
track: False
pth: /home/programmer/4_master/udacity/MachineLearningDevOpsEngineer/1_Project_Predict_Customer_Churn
train_models: False
grid_search: False
data:
  file_name: BankChurners.csv
  split_ratio: 0.8
  col_name_max_length: 30

plot:
     figsize: (15, 8)
     alpha: 0.8


job_logging:
    name: ${hydra:job.name}
    root:
      handlers: [console, file]

    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: basic
      file:
        class : logging.FileHandler
        filename: ${hydra:job.name}_${hydra:job.num}.log  # this will name the log file with your job's name and id
        formatter: basic
        level: INFO

    formatters:
      basic:
        format: '%(asctime)s [%(levelname)s] - %(name)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
